package app;

/**
* app/FrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontend.idl
* Friday, 25 March 2022 18:40:16 o'clock EDT
*/

public final class FrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public app.FrontEnd value = null;

  public FrontEndHolder ()
  {
  }

  public FrontEndHolder (app.FrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = app.FrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    app.FrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return app.FrontEndHelper.type ();
  }

}
