package app;


/**
* app/FrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from frontend.idl
* Friday, 25 March 2022 18:40:16 o'clock EDT
*/

public interface FrontEnd extends FrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEnd
